#!/usr/bin/env python
import os
import django
import psycopg2
from django.conf import settings

# Configurar Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'tienda_backend.settings')
django.setup()

# SQL para crear las tablas de core
SQL_QUERIES = [
    """CREATE TABLE "core_tienda" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(100) NOT NULL, "direccion" text NOT NULL);""",
    """CREATE TABLE "core_usuario" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "telefono" varchar(15) NULL);""",
    """CREATE TABLE "core_usuario_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "group_id" integer NOT NULL);""",
    """CREATE TABLE "core_usuario_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "usuario_id" bigint NOT NULL, "permission_id" integer NOT NULL);""",
    """ALTER TABLE "core_tienda" ADD COLUMN "propietario_id" bigint NOT NULL CONSTRAINT "core_tienda_propietario_id_f8a33b4e_fk_core_usuario_id" REFERENCES "core_usuario"("id") DEFERRABLE INITIALLY DEFERRED;""",
    """SET CONSTRAINTS "core_tienda_propietario_id_f8a33b4e_fk_core_usuario_id" IMMEDIATE;""",
    """CREATE TABLE "core_producto" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "nombre" varchar(100) NOT NULL, "categoria" varchar(50) NOT NULL, "precio" numeric(10, 2) NOT NULL, "cantidad" integer NOT NULL CHECK ("cantidad" >= 0), "codigo_barras" varchar(50) NULL UNIQUE, "tienda_id" bigint NOT NULL);""",
    """CREATE TABLE "core_configuracion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "pedidos_por_voz" boolean NOT NULL, "stock_minimo_alerta" integer NOT NULL CHECK ("stock_minimo_alerta" >= 0), "tienda_id" bigint NOT NULL UNIQUE);""",
    """CREATE TABLE "core_caja" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "saldo_inicial" numeric(10, 2) NOT NULL, "saldo_final" numeric(10, 2) NULL, "fecha_apertura" timestamp with time zone NOT NULL, "fecha_cierre" timestamp with time zone NULL, "estado" varchar(10) NOT NULL, "tienda_id" bigint NOT NULL);""",
    """CREATE TABLE "core_gasto" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fecha" timestamp with time zone NOT NULL, "descripcion" text NOT NULL, "monto" numeric(10, 2) NOT NULL, "categoria" varchar(50) NOT NULL, "caja_id" bigint NOT NULL, "tienda_id" bigint NOT NULL, "usuario_id" bigint NOT NULL);""",
    """CREATE TABLE "core_empleado" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fecha_contratacion" date NOT NULL, "tienda_id" bigint NOT NULL, "usuario_id" bigint NOT NULL UNIQUE);""",
    """ALTER TABLE "core_caja" ADD COLUMN "usuario_id" bigint NOT NULL CONSTRAINT "core_caja_usuario_id_0750c176_fk_core_usuario_id" REFERENCES "core_usuario"("id") DEFERRABLE INITIALLY DEFERRED;""",
    """SET CONSTRAINTS "core_caja_usuario_id_0750c176_fk_core_usuario_id" IMMEDIATE;""",
    """CREATE TABLE "core_venta" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "fecha" timestamp with time zone NOT NULL, "total" numeric(10, 2) NOT NULL, "caja_id" bigint NOT NULL, "tienda_id" bigint NOT NULL, "usuario_id" bigint NOT NULL);""",
    """CREATE TABLE "core_detalleventa" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "cantidad" integer NOT NULL CHECK ("cantidad" >= 0), "precio_unitario" numeric(10, 2) NOT NULL, "producto_id" bigint NOT NULL, "venta_id" bigint NOT NULL);""",
    """CREATE INDEX "core_producto_tienda_id" ON "core_producto" ("tienda_id");""",
    """CREATE INDEX "core_configuracion_tienda_id" ON "core_configuracion" ("tienda_id");""",
    """CREATE INDEX "core_caja_tienda_id" ON "core_caja" ("tienda_id");""",
    """CREATE INDEX "core_gasto_caja_id" ON "core_gasto" ("caja_id");""",
    """CREATE INDEX "core_gasto_tienda_id" ON "core_gasto" ("tienda_id");""",
    """CREATE INDEX "core_gasto_usuario_id" ON "core_gasto" ("usuario_id");""",
    """CREATE INDEX "core_empleado_tienda_id" ON "core_empleado" ("tienda_id");""",
    """CREATE INDEX "core_empleado_usuario_id" ON "core_empleado" ("usuario_id");""",
    """CREATE INDEX "core_venta_caja_id" ON "core_venta" ("caja_id");""",
    """CREATE INDEX "core_venta_tienda_id" ON "core_venta" ("tienda_id");""",
    """CREATE INDEX "core_venta_usuario_id" ON "core_venta" ("usuario_id");""",
    """CREATE INDEX "core_detalleventa_producto_id" ON "core_detalleventa" ("producto_id");""",
    """CREATE INDEX "core_detalleventa_venta_id" ON "core_detalleventa" ("venta_id");""",
]

# Conectar y ejecutar
try:
    db_config = settings.DATABASES['default']
    conn = psycopg2.connect(
        dbname=db_config['NAME'],
        user=db_config['USER'],
        password=db_config['PASSWORD'],
        host=db_config['HOST'],
        port=db_config['PORT'],
        sslmode='require'
    )
    cursor = conn.cursor()
    
    for query in SQL_QUERIES:
        try:
            cursor.execute(query)
            print(f"✓ Ejecutado: {query[:50]}...")
        except psycopg2.errors.DuplicateTable:
            print(f"⊘ Tabla ya existe: {query[:50]}...")
        except Exception as e:
            print(f"✗ Error: {e}")
    
    conn.commit()
    cursor.close()
    conn.close()
    print("\n✓ Base de datos configurada correctamente")
    
except Exception as e:
    print(f"✗ Error de conexión: {e}")
