# Generated by Django 5.1.7 on 2026-04-12

from django.db import migrations


def set_admin_role_for_staff_and_superusers(apps, schema_editor):
    Usuario = apps.get_model('core', 'Usuario')
    Usuario.objects.filter(is_superuser=True).update(rol='administrador')
    Usuario.objects.filter(is_staff=True).update(rol='administrador')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_rol'),
    ]

    operations = [
        migrations.RunPython(set_admin_role_for_staff_and_superusers, migrations.RunPython.noop),
    ]
